# .github/workflows/deploy.yml
name: Deploy SvelteKit to GitHub Pages

on:
  push:
    branches: [main] # Make sure this matches your default branch (e.g., 'main' or 'master')
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          # We'll rely on Yarn's own caching, so no need for npm cache here
          # cache: 'npm'
          # cache-dependency-path: package-lock.json

      - name: Install Yarn # <--- NEW STEP: Install Yarn globally
        run: npm install -g yarn

      # No need for manual node_modules cleanup, Yarn handles it
      # - name: Clean node_modules
      #   run: rm -rf node_modules
      #   continue-on-error: true

      # No need to upgrade npm explicitly anymore
      # - name: Upgrade npm
      #   run: npm install -g npm@latest

      - name: Install dependencies with Yarn # <--- CHANGED: Use 'yarn install'
        run: yarn install --frozen-lockfile # --frozen-lockfile is like npm ci, for strictness in CI

      - name: Build SvelteKit app with Yarn # <--- CHANGED: Use 'yarn build'
        run: yarn build

      - name: Setup Pages
        uses: actions/configure-pages@v5
        with:
          static_site_generator: sveltekit

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './build'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4